### ISSUE TITLE
RPC method eth_estimateGas crashed

### ISSUE THREAD

**Issue by eastata** [clearmatics/autonity#681] opened 2020-09-23 14:34 UTC
# Problem

If autonity not a validator RPC call **eth_estimateGas** crached:
  * flags `--mine --minerthreads 1` disabled
  * enode in autonity contract whitelist, but without stake

If autonity is a validator crash not happens

# How to reproduce

* deploy 
  ```
  helm install ap-test --namespace ap-test charts-ose.clearmatics.com/autonity-network --version 1.8.0 --set validators.num=2,observers.num=1,networkid=444900
  ```
* Get a treasury private key
  ```
  kubectl -n ap-test get secrets operator-treasury -o 'go-template={{index .data "0.private_key"}}' | base64 --decode; echo ""
  ```
* Forward RPC port to localhost
  ```
  kubectl -n ap-test port-forward svc/observer-0 8545:8545
  ```
* Prepare `./truffle-config.js` like
```js
const PrivateKeyProvider = require("truffle-privatekey-provider");
const PRIVATE_KEY = "8dbe71a7960125334e6a969eebc10455d190cd2eabc8416bf594b7254f7c4967"
const AUTONITY_RPC = "http://127.0.0.1:8545"
const GAS_PRICE = 10000000000000
const NETWORK_ID = 444900

module.exports = {
  networks: {
  development: {
    skipDryRun: true,
    provider: new PrivateKeyProvider(PRIVATE_KEY, AUTONITY_RPC),
    gas: 10000000,
    gasPrice: GAS_PRICE,
    network_id: NETWORK_ID
    }
  },
  mocha: {
  },
  compilers: {
      solc: {
      version: "0.5.3",    // Fetch exact version from solc-bin (default: truffle's version)
      }
  }
}
```
* Call using `js`
```js
    const amount = "555"
    const recipient = "0xD3c9726aAECc5B2a1DF47378BE470523791d1a0b"

    const accounts = await web3.eth.getAccounts()
    const sender = accounts[0]

    const tx = await web3.eth.sendTransaction({ from: sender, to: recipient, value: amount })
```
# Nginx RPC request logs
```
[23/Sep/2020:14:03:07 +0000] "127.0.0.1" "200" "POST / HTTP/1.1" "req_time 0.017" {\"id\":1,\"jsonrpc\":\"2.0\",\"params\":[],\"method\":\"eth_blockNumber\",\"skipCache\":true}
[23/Sep/2020:14:03:07 +0000] "127.0.0.1" "200" "POST / HTTP/1.1" "req_time 0.018" {\"id\":1,\"jsonrpc\":\"2.0\",\"params\":[],\"method\":\"eth_blockNumber\"}
[23/Sep/2020:14:03:07 +0000] "127.0.0.1" "200" "POST / HTTP/1.1" "req_time 0.015" {\"id\":1600869787392208,\"jsonrpc\":\"2.0\",\"params\":[\"0x37f\",false],\"method\":\"eth_getBlockByNumber\",\"skipCache\":true}
[23/Sep/2020:14:03:07 +0000] "127.0.0.1" "200" "POST / HTTP/1.1" "req_time 0.011" {\"id\":2,\"jsonrpc\":\"2.0\",\"params\":[],\"method\":\"net_version\"}
[23/Sep/2020:14:03:07 +0000] "127.0.0.1" "200" "POST / HTTP/1.1" "req_time 0.016" {\"id\":5,\"jsonrpc\":\"2.0\",\"params\":[\"0x0040618ae0b8e7a3b21b7ea91eb0ff17110ae445\",\"latest\"],\"method\":\"eth_getBalance\"}
[23/Sep/2020:14:03:07 +0000] "127.0.0.1" "200" "POST / HTTP/1.1" "req_time 0.015" {\"id\":6,\"jsonrpc\":\"2.0\",\"params\":[],\"method\":\"eth_gasPrice\"}
[23/Sep/2020:14:03:07 +0000] "127.0.0.1" "200" "POST / HTTP/1.1" "req_time 0.013" {\"id\":1600869787537782,\"jsonrpc\":\"2.0\",\"params\":[\"0x0040618ae0b8e7a3b21b7ea91eb0ff17110ae445\",\"pending\"],\"method\":\"eth_getTransactionCount\"}
[23/Sep/2020:14:03:07 +0000] "127.0.0.1" "200" "POST / HTTP/1.1" "req_time 0.014" {\"id\":1600869787537598,\"jsonrpc\":\"2.0\",\"params\":[{\"from\":\"0x0040618ae0b8e7a3b21b7ea91eb0ff17110ae445\",\"to\":\"0xd3c9726aaecc5b2a1df47378be470523791d1a0b\",\"value\":\"0x22b\",\"gasPrice\":\"0x9184e72a000\"}],\"method\":\"eth_estimateGas\"}
```

# Autonity error logs
```
ERROR[09-23|14:03:07.577] RPC method eth_estimateGas crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 17546 [running]:
github.com/clearmatics/autonity/rpc.(*callback).call.func1(0xc0034b68d0, 0xf, 0xc002fcbd50)
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/rpc/service.go:200 +0xb5
panic(0x1096b80, 0x1cf60c0)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/clearmatics/autonity/core/types.(*Block).GasLimit(...)
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/core/types/block.go:483
github.com/clearmatics/autonity/internal/ethapi.DoEstimateGas(0x14d9520, 0xc00356d500, 0x14f5640, 0xc000484900, 0xc00397a960, 0xc00397a980, 0x0, 0xc003068700, 0xc0030686e0, 0x0, ...)
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/internal/ethapi/api.go:944 +0xc41
github.com/clearmatics/autonity/internal/ethapi.(*PublicBlockChainAPI).EstimateGas(0xc0004d2480, 0x14d9520, 0xc00356d500, 0xc00397a960, 0xc00397a980, 0x0, 0xc003068700, 0xc0030686e0, 0x0, 0x0, ...)
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/internal/ethapi/api.go:1032 +0xf2
reflect.Value.call(0xc00050b780, 0xc000a18630, 0x13, 0x1209507, 0x4, 0xc00302c910, 0x3, 0x3, 0xc005ab3be8, 0x46931c, ...)
	/usr/local/go/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0xc00050b780, 0xc000a18630, 0x13, 0xc00302c910, 0x3, 0x3, 0x1, 0x1, 0x0)
	/usr/local/go/src/reflect/value.go:321 +0xb4
github.com/clearmatics/autonity/rpc.(*callback).call(0xc000a31e60, 0x14d9520, 0xc00356d500, 0xc0034b68d0, 0xf, 0xc0030686c0, 0x1, 0x1, 0x0, 0x0, ...)
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/rpc/service.go:206 +0x2b7
github.com/clearmatics/autonity/rpc.(*handler).runMethod(0xc003c87560, 0x14d9520, 0xc00356d500, 0xc0030c7110, 0xc000a31e60, 0xc0030686c0, 0x1, 0x1, 0x1)
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/rpc/handler.go:389 +0x8a
github.com/clearmatics/autonity/rpc.(*handler).handleCall(0xc003c87560, 0xc00377e630, 0xc0030c7110, 0xc0005bf6c0)
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/rpc/handler.go:337 +0x298
github.com/clearmatics/autonity/rpc.(*handler).handleCallMsg(0xc003c87560, 0xc00377e630, 0xc0030c7110, 0x14c5201)
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/rpc/handler.go:298 +0x1bd
github.com/clearmatics/autonity/rpc.(*handler).handleMsg.func1(0xc00377e630)
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/rpc/handler.go:139 +0x46
github.com/clearmatics/autonity/rpc.(*handler).startCallProc.func1(0xc003c87560, 0xc003068680)
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/rpc/handler.go:226 +0xcd
created by github.com/clearmatics/autonity/rpc.(*handler).startCallProc
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/rpc/handler.go:222 +0x66
 
WARN [09-23|14:03:07.577] Served eth_estimateGas                   conn=127.0.0.1:57284 reqid=1600869787537598 t="288.865µs" err="method handler crashed"

```

# Acceptance Criteria

* RPC method eth_estimateGas not crashed
* Tools that use RPC method **eth_estimateGas** works like [web3.eth.sendTransaction](https://web3js.readthedocs.io/en/v1.2.11/web3-eth.html#sendtransaction)

# Notes

If you call validator instead observer like
```
kubectl -n ap-test port-forward svc/validator-0 8545:8545
```
RPC call will handled correct

Flags could be founded here: https://github.com/clearmatics/charts-ose-helm3/blob/c7ec6c924a9be796cd624acb85f37912101edfe0/stable/autonity-network/templates/deployments_observers.yaml#L57-L85

# Versions
Reproduced for:

* autonity-network-1.7.1 (autonity `v0.4.0`)
* autonity-network-1.8.0 (autonity `v0.6.0`)

# Future Steps

Steps which should be taken after this issue has been resolved.
* Release docker image with fix
* Update helm charts [autonity-network](https://github.com/clearmatics/charts-ose-helm3/tree/master/stable/autonity-network) and [autonity](https://github.com/clearmatics/charts-ose-helm3/tree/master/stable/autonity)

**Comment by AntoineRondelet** [comment] 2020-09-23 14:49
Oh,  https://github.com/clearmatics/zeth/issues/281 may be related to this issue then. As I didn't have access to the node I RPC'ed I didn't have access to all the logs. Since I witnessed the crash on some TLS-enabled nodes that was my only clue, but maybe they weren't validators - which would be in line with what you say here @eastata (I don't see how TLS can make things crash to be honest so I hope I was mislead by some funny circumstances)

**Comment by eastata** [comment] 2020-09-23 14:54
@AntoineRondelet 
**tls** definitely not related for this issue.
* All public available RPC for `TestNet` exposed by participants (not by validators)
* You can deploy helm chart using instructions above and test zeth issue using validators rpc
  * As a feature you can have access to nginx/rpc logs for troubleshooting

**Comment by AntoineRondelet** [comment] 2020-09-23 15:00
> You can deploy helm chart using instructions above and test zeth issue using validators rpc
>    As a feature you can have access to nginx/rpc logs for troubleshooting

Thanks @eastata that's helpful, will give this a try - will certainly make our life easier for troubleshooting indeed

**Comment by piersy** [comment] 2020-09-23 15:13
Hi @eastata this is a problem that originates from the ethereum codebase.

The problem is that estimate gas assumes that the miner has a "pending block" but the miner only gets a pending block either after it has received a transaction or it has been told to start mining and has a potential block.

So if mining is disabled on a node this rpc call will fail until a transaction is sent to the node.

**Comment by eastata** [comment] 2020-09-23 15:30
@AntoineRondelet workaround for `web3`  to avoid call  `eth_estimateGas`:
```
const tx = await web3.eth.sendTransaction({ from: sender, to: recipient, value: amount, gas: 10000000 })
```

**Comment by AntoineRondelet** [comment] 2020-09-23 15:59
> @AntoineRondelet workaround for `web3` to avoid call `eth_estimateGas`:
> 
> ```
> const tx = await web3.eth.sendTransaction({ from: sender, to: recipient, value: amount, gas: 10000000 })
> ```

Yes I have a broken PR for that: https://github.com/clearmatics/zeth/pull/282/files already, but was keen to get the `estimateGas` working instead of hardcoding gas values everywhere (or adding them as extra arguments to be set by the user). Looks like we'll need to do that then..

**Comment by yazzaoui** [comment] 2020-09-23 16:21
> Hi @eastata this is a problem that originates from the ethereum codebase.
> 
> The problem is that estimate gas assumes that the miner has a "pending block" but the miner only gets a pending block either after it has received a transaction or it has been told to start mining and has a potential block.
> 
> So if mining is disabled on a node this rpc call will fail until a transaction is sent to the node.

Yes, related issue : https://github.com/ethereum/go-ethereum/issues/2586

And according to the spec (https://eth.wiki/json-rpc/API):

> If no gas limit is specified geth uses the block gas limit **from the pending block** as an upper bound. As a result the returned estimate might not be enough to executed the call/transaction when the amount of gas is higher than the pending block gas limit.

**Comment by piersy** [comment] 2020-09-23 17:22
@eastata @yazzaoui 

Its a combination of ethereum code and our code.

The reason we see this problem, but it's not manifesting in geth is that we changed the way the miner worker was started in 
https://github.com/clearmatics/autonity/commit/9005eab249ed8b3fe72fdbe6ce31148721a42d51#diff-7fc2e947b54d13e96c3477dc4e6e6c06R77-R78. ([PR](https://github.com/clearmatics/autonity/pull/421/files))

We changed the last parameter "init" to be false. If this was instead true the miner worker would set their pending block very soon after being created. As it stands this now does not happen until I think, the node either receives a transaction or mining is started.

Unfortunately there was a lot of code changed in that PR and it lacks any detailed explanation of exactly what was fixed and how the fixes are working, so its hard to say where we stand with this, or to know how we could fix it.

**Comment by AntoineRondelet** [comment] 2020-09-24 14:58
Thanks @piersy @yazzaoui for the details/links above.
I am not familiar with all of this. Quick note, however that passing very big gas values per calls (say, not relying on any gas estimate for the calls and setting say gas=100000000000000000 - related to https://github.com/clearmatics/autonity/issues/681#issuecomment-697547375) can prove to be dangerous when interacting with poorly designed contracts that can throw asserts (an `assert` consume all gas available to the call if it is reached). While this is **plain bad practice/mistake for a contract to throw an assert**, that's still something to be aware of, so if this issue can be fixed on Autonity at some point, that would be great to make sure most tooling can rely on the `estimateGas` function to have some rough estimate on the gas used by a transaction (user input may still need to be requested, but most users will likely have no prior knowledge on the gas used by their transactions). Overall that would be a nice UX improvement I believe.

**Comment by yazzaoui** [comment] 2020-10-01 00:10
Closing in favor of #694 .
We will fix it for our next release but please don't expect any hotfix in the meantime.

As a temporary workaround, you can, in order of preference:
- Do some manual estimates, users would enjoy knowing how much are they likely to spend on transactions as gas is not free.
- Enable mining for the nodes you are requesting gas estimation. They don't need to be validators and the error message you'll see (`consensus :not authorized`) if a non-validator node is mining is harmless.
- Set a predefined high gas value, we know what are the contracts being demoed in the testnet and they should not throw asserts.

**Closed by yazzaoui** 2020-10-01 00:10 UTC
Labels: bug, triage
