### ISSUE TITLE
Segfault when launching Autonity from genesis block

### ISSUE THREAD

**Issue by szemate** [clearmatics/autonity#308] opened 2019-10-03 17:03 UTC
# Problem
Unable to launch Autonity (version 0.2.1) following the steps below because start-up results in segmentation fault. Not sure if it's a bug or configuration error, any help would be appreciated.

The last working commit is aed64a5 i.e. the error should be related to network economics.

# Steps to reproduce
1. Save a password into a passfile to be used with the wallet
2. Generate 4 accounts with
```
autonity --datadir ~/workspace --password passfile account new
```
3. Save the accounts' private keys into nodekey files
4. Generate the nodes' public keys with
```
bootnode -writeaddress -nodekey nodekeyX
```
5. Create genesis.json (see below, based on local_test_network/genesis.json)
6. Initialise chain data with
```
autonity -datadir ~/workspace init genesis.json
```
7. Launch Autonity with
```
autonity \
--datadir ~/workspace \
--nodekey nodekey1 \
--syncmode full \
--port 5545 \
--rpc --rpcport 6058 --rpcaddr 127.0.0.1 --rpccorsdomain '*' \
--rpcapi personal,db,eth,net,web3,txpool,miner,tendermint,clique \
--networkid 1756 \
--miner.gasprice 0 \
--allow-insecure-unlock --unlock 0xba1f6167b504960880a3b85cf5873347d0a5032d \
--password passfile \
--debug --verbosity 4 \
--mine --miner.threads 1 --miner.etherbase 0xba1f6167b504960880a3b85cf5873347d0a5032d
```

# Error log
```
DEBUG[10-03|17:43:19.596|autonity/main.go:265] Sanitizing Go's GC trigger               percent=100
INFO [10-03|17:43:19.597|cmd/utils/flags.go:1102] Maximum peer count                       ETH=50 LES=0 total=50
INFO [10-03|17:43:19.597|cmd/utils/flags.go:1176] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
DEBUG[10-03|17:43:19.597|accounts/keystore/file_cache.go:87] FS scan times                            list=18.453µs set=2.407µs diff=1.279µs
INFO [10-03|17:43:19.599|node/node.go:190]                   Starting peer-to-peer node               instance=Autonity/v0.2.1-ae070c2a-20191002/linux-amd64/go1.12
WARN [10-03|17:43:19.599|eth/backend.go:135]                 Sanitizing invalid miner gas price       provided=0 updated=0
INFO [10-03|17:43:19.599|eth/backend.go:142]                 Allocated trie memory caches             clean=256.00MiB dirty=256.00MiB
INFO [10-03|17:43:19.599|ethdb/leveldb/leveldb.go:91]        Allocated cache and file handles         database=/tmp/autonity.4_yq54vt/0xba1f6167b504960880a3b85cf5873347d0a5032d/autonity/chaindata cache=512.00MiB handles=262144
DEBUG[10-03|17:43:19.603|core/rawdb/freezer_table.go:305]    Chain freezer table opened               database=/tmp/autonity.4_yq54vt/0xba1f6167b504960880a3b85cf5873347d0a5032d/autonity/chaindata/ancient table=headers items=0 size=0.00B
DEBUG[10-03|17:43:19.603|core/rawdb/freezer_table.go:305]    Chain freezer table opened               database=/tmp/autonity.4_yq54vt/0xba1f6167b504960880a3b85cf5873347d0a5032d/autonity/chaindata/ancient table=hashes  items=0 size=0.00B
DEBUG[10-03|17:43:19.603|core/rawdb/freezer_table.go:305]    Chain freezer table opened               database=/tmp/autonity.4_yq54vt/0xba1f6167b504960880a3b85cf5873347d0a5032d/autonity/chaindata/ancient table=bodies  items=0 size=0.00B
DEBUG[10-03|17:43:19.603|core/rawdb/freezer_table.go:305]    Chain freezer table opened               database=/tmp/autonity.4_yq54vt/0xba1f6167b504960880a3b85cf5873347d0a5032d/autonity/chaindata/ancient table=receipts items=0 size=0.00B
DEBUG[10-03|17:43:19.603|core/rawdb/freezer_table.go:305]    Chain freezer table opened               database=/tmp/autonity.4_yq54vt/0xba1f6167b504960880a3b85cf5873347d0a5032d/autonity/chaindata/ancient table=diffs    items=0 size=0.00B
INFO [10-03|17:43:19.603|core/rawdb/freezer.go:123]          Opened ancient database                  database=/tmp/autonity.4_yq54vt/0xba1f6167b504960880a3b85cf5873347d0a5032d/autonity/chaindata/ancient
DEBUG[10-03|17:43:19.603|core/rawdb/freezer.go:273]          Current full block not old enough        number=0 hash=ab1a97…3b764d delay=90000
INFO [10-03|17:43:19.603|eth/backend.go:168]                 Initialised chain configuration          config="{ChainID: 1991 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: <nil>  Petersburg: <nil> Engine: tendermint}"
WARN [10-03|17:43:19.603|consensus/tendermint/backend/backend.go:60] new backend with public key              backAddress=0xBa1F6167b504960880a3B85Cf5873347D0a5032D
INFO [10-03|17:43:19.603|eth/backend.go:212]                         Initialising Ethereum protocol           versions=[63] network=1756
WARN [10-03|17:43:19.603|eth/backend.go:218]                         Upgrade blockchain database version      from=<nil> to=7
INFO [10-03|17:43:19.660|core/blockchain.go:382]                     Loaded most recent local header          number=0 hash=ab1a97…3b764d td=1 age=50y5mo3w
INFO [10-03|17:43:19.660|core/blockchain.go:383]                     Loaded most recent local full block      number=0 hash=ab1a97…3b764d td=1 age=50y5mo3w
INFO [10-03|17:43:19.661|core/blockchain.go:384]                     Loaded most recent local fast block      number=0 hash=ab1a97…3b764d td=1 age=50y5mo3w
DEBUG[10-03|17:43:19.661|core/tx_pool.go:1132]                       Reinjecting stale transactions           count=0
INFO [10-03|17:43:19.661|core/tx_journal.go:166]                     Regenerated local transaction journal    transactions=0 accounts=0
DEBUG[10-03|17:43:19.661|eth/downloader/downloader.go:1799]          Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc1b952]

goroutine 102 [running]:
github.com/clearmatics/autonity/consensus/tendermint/backend.(*Backend).getValidators(0xc00053c3c0, 0xc008de6000, 0x1411900, 0xc008d72000, 0xc008df8120, 0x0, 0x0, 0x0, 0x0, 0x0)
	/ext-go/1/src/github.com/clearmatics/autonity/consensus/tendermint/backend/engine.go:385 +0x152
github.com/clearmatics/autonity/consensus/tendermint/backend.(*Backend).FinalizeAndAssemble(0xc00053c3c0, 0x1411900, 0xc008d72000, 0xc008de6000, 0xc008df8120, 0x0, 0x0, 0x0, 0xc0000ae440, 0x0, ...)
	/ext-go/1/src/github.com/clearmatics/autonity/consensus/tendermint/backend/engine.go:352 +0x7f
github.com/clearmatics/autonity/consensus/tendermint/core.(*core).FinalizeAndAssemble(0xc00053c500, 0x1411900, 0xc008d72000, 0xc008de6000, 0xc008df8120, 0x0, 0x0, 0x0, 0xc0000ae440, 0x0, ...)
	/ext-go/1/src/github.com/clearmatics/autonity/consensus/tendermint/core/core_backend.go:49 +0xf2
github.com/clearmatics/autonity/miner.(*worker).commit(0xc000512ea0, 0xc0000ae440, 0x0, 0x2, 0x0, 0x1, 0xbf5da729e76e26a1, 0x56d0772, 0x1f80380, 0x0, ...)
	/ext-go/1/src/github.com/clearmatics/autonity/miner/worker.go:986 +0x268
github.com/clearmatics/autonity/miner.(*worker).commitNewWork(0xc000512ea0, 0xc0001b6010, 0x0, 0x5d962527)
	/ext-go/1/src/github.com/clearmatics/autonity/miner/worker.go:973 +0x8df
github.com/clearmatics/autonity/miner.(*worker).mainLoop(0xc000512ea0)
	/ext-go/1/src/github.com/clearmatics/autonity/miner/worker.go:425 +0xc00
created by github.com/clearmatics/autonity/miner.newWorker
	/ext-go/1/src/github.com/clearmatics/autonity/miner/worker.go:217 +0x502
```

# Genesis file used
```json
{
    "config": {
        "homesteadBlock": 0,
        "eip150Block": 0,
        "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "eip155Block": 0,
        "eip158Block": 0,
        "byzantiumBlock": 0,
        "tendermint": {
            "policy": 0,
            "epoch": 30000,
            "contract-deployer": "0x0000000000000000000000000000000000000001",
            "bytecode": "",
            "abi": ""
        },
        "chainId": 1991,
        "enodeWhitelist": [
            "enode://4696c5e2e6a07aa7fb455a1c170e6496df715784c52833e16122deedd6bbe1f33bf1a217cd8036fab4f604efbda5282c138665fa0af8388612006dc53cdaefd1@127.0.0.1:5598",
            "enode://e97002b7d51dade5b0df596abec0c4b36d474be74a8048eab0f571fb5e3632b1299ad0e7c533d0f9586b073c06a7f578191c250454e0958311dc542dc6014abd@127.0.0.1:5516",
            "enode://f70018146a4b11350e890a1d56d191721f3d882096e50d12d98ca98baac95e769d2b921b424ead648676a46b1896951c188b0cbda5b28b98c97fcfa9f4094f0d@127.0.0.1:5556",
            "enode://3f485ec832eff92052b935594ae18a48e634ac14139c21d2ad3dbae962e1ce4d3eaf68603bd1c98c236238b5b93493ab92d3d1612ebaa4bc85b1732cf78b4cf0@127.0.0.1:5502"
        ],
        "glienickeDeployer": "0x0000000000000000000000000000000000000001",
        "glienickeBytecode": "",
        "glienickeABI": ""
    },
    "nonce": "0x0",
    "timestamp": "0x0",
    "gasLimit": "0x5f5e100",
    "difficulty": "0x1",
    "coinbase": "0x0000000000000000000000000000000000000000",
    "number": "0x0",
    "gasUsed": "0x0",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
    "alloc": {
        "0xba1f6167b504960880a3b85cf5873347d0a5032d": {
            "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
        },
        "0x157b1bcb9be54bf62aabe93d1a24875318fa2691": {
            "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
        },
        "0xe916f00ee55384fd130cb2d83f0ef11e364bd23d": {
            "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
        },
        "0xe76c2105e5e3cb3dddcdf9c238fbb0940a428ab0": {
            "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
        }
    },
    "validators": [
        "0xba1f6167b504960880a3b85cf5873347d0a5032d",
        "0x157b1bcb9be54bf62aabe93d1a24875318fa2691",
        "0xe916f00ee55384fd130cb2d83f0ef11e364bd23d",
        "0xe76c2105e5e3cb3dddcdf9c238fbb0940a428ab0"
    ]
}
```

**Comment by yazzaoui** [comment] 2019-10-04 12:01
Hello @szemate 

Your genesis file configuration was depreciated with the 0.2 release, the python local deployment script were recently updated if you need them as a reference and the new genesis.json description can be found [here](https://github.com/clearmatics/autonity/wiki/Genesis-File-Configuration) .

But in any cases, the client shouldn't panic and should gracefully stop.

**Comment by b00ris** [comment] 2019-10-14 09:51
Should we close the issue?

**Comment by JekaMas** [comment] 2019-10-14 09:51
@szemate Does it work now or the issue is still reproducible?

**Comment by szemate** [comment] 2019-10-14 10:05
> Does it work now or the issue is still reproducible?

Still the same error message if I'm using the wrong genesis file. I think it would be helpful to have a correct error message if certain fields are missing from genesis.json.

**Comment by yazzaoui** [comment] 2019-10-14 14:08
@b00ris do you mind having a look at this ?

**Closed** 2019-12-09 13:35 UTC
Labels: Sprint 16, bug
